# =============================================================================
# application-aws.yml -- Perfil 'aws' (Lambda en produccion)
# =============================================================================
app:
  aws:
    region: ${AWS_REGION_NAME:us-east-1}
    sns-topic-arn: ${SNS_TOPIC_ARN:}
