# =============================================================================
# application-local.yml -- Perfil 'local'
# =============================================================================
app:
  aws:
    region: us-east-1
    sns-topic-arn:
