# =============================================================================
# application.yml -- Configuracion comun (Notification v3)
# =============================================================================
spring:
  main:
    banner-mode: off
    web-application-type: servlet
  application:
    name: msg-pipeline-notification-v3

logging:
  level:
    root: INFO
    com.msgpipeline: INFO
    software.amazon.awssdk: WARN
